### ISSUE TITLE
Catch all internal errors

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/wejam#11]
Due to the promise-based code, if we want to handle internal errors we have to do that:

```
async function myRoute (req, res) {
  try {
      .... // do stuff
  } catch (e) {
    res.errorPage(500, e)
  }
}
```

A bit verbose if we duplicate this on every route...

Some possible solutions are [listed here](http://stackoverflow.com/questions/33410101/unhandled-rejections-in-express-applications). We could also make a custom wrapper for our routes.

**Comment by ttencate** [comment]
If an exception occurs, the request just hangs without a proper error being sent to the client. It is being logged to the console by the `unhandledRejection` handler, but that's at the Node level so it doesn't have access to the Express response.

In Express, you're supposed to call `next(err)` if an error occurs, not just return a rejected promise. I think https://github.com/express-promise-router/express-promise-router is made to solve exactly this problem.
