### ISSUE TITLE
Fix horizontal alignment

### ISSUE THREAD

**Issue by ttencate** [mkalam-alami/wejam#15]
Various elements of the pages aren't horizontally aligned: they either stick out into the left/right margin, or are indented on the left/right. This is because of assumptions Bootstrap makes: rows may only contain cols, and containers must not be nested. So the typical hierarchy is:

    container > row > col > row > col > ...

Nesting of containers will mess up the padding, because containers add padding that is supposed to be cancelled out by negative margins in the rows.

This is easy to fix by removing superfluous containers, and adding some extra divs where necessary.

**Comment by ttencate** [comment]
Working on this now, but I can't assign this to myself because @mkalam-alami is hoarding all the permissions to himself ;)

**Comment by mkalam-alami** [comment]
Ok just found the [relevant](http://getbootstrap.com/css/#overview-container) [docs](http://getbootstrap.com/css/#grid-nesting), good to know.

The only slightly tricky part you might find is for "event tables/entry thumbnails" macros: I tried nesting a fluid container below the main one to make thumbnails resizable. You can scrap it all away and only keep the default width.

**Comment by ttencate** [comment]
A fluid container isn't necessary for that; rows already span 100% width anyway. Pretty much all that `.container-fluid` does is set some padding left and right.

**Comment by mkalam-alami** [comment]
Unless I'm mistaken it did make some difference though:

*  `.col-md-6 > .row > .col-md-6` fills the full parent column
* `.col-md-6 > .container-fluid > .row > .col-md-6` fills half of that.

Basically putting a fluid container in a column divides the column into 12 again, which felt like it could have its use.

**Comment by mkalam-alami** [comment]
For reference, some googling suggests that nesting containers can actually have its uses, but is officially discouraged right now due to the padding issue & possible mobile/browser-specific complications. ([1](http://stackoverflow.com/a/29701307/1213677), [2](http://stackoverflow.com/questions/33258791/can-you-nest-bootstrap-containers), [3](https://github.com/twbs/bootstrap/issues/11436))

**Comment by ttencate** [comment]
It does not fill the full parent column for me: http://plnkr.co/edit/SEZ5r9eUrkT8NRKxUMsz?p=preview Perhaps your window is narrower? `col-md-6` only takes effect at somewhat big screens, like tablets. In my plunk I used `col-xs-6` which takes effect at all screen sizes.

FWIW, Bootstrap 4 (alpha) uses flexbox and might be nicer in this respect: https://blog.getbootstrap.com/2017/01/06/bootstrap-4-alpha-6/ I would think the base Bootstrap 4 library would be usable enough already, but I don't know whether any plugins are already compatible, or whether they even need to be changed in order to keep working.

**Comment by mkalam-alami** [comment]
Oh. Yes I guess I jumped a wrong conclusion by using `col-sm/col-md` on a narrow column. Thanks for checking this, it will make future grid building easier.
