### ISSUE TITLE
Normalize indenting

### ISSUE THREAD

**Issue by mkalam-alami** [mkalam-alami/wejam#16]
Sublime Text doesn't indent [Standard JS](https://standardjs.com/) correctly: JSDoc tags just offset everything by 1 space or more, and `standard --fix` doesn't even fix that. I've tried various Sublime Text plugins without success.

I can't find any similar issues on the web though so maybe it's a local problem.

[example](https://github.com/mkalam-alami/wejam/blob/master/services/session-service.js)

**Comment by mkalam-alami** [comment]
Finally figured this out. There is a trailing space in the first line of some files `[ ]'use strict'` which is making the linter offset everything. I'll fix it once we're done with #6 and #18 heavy-duty to prevent merge issues.

**Comment by ttencate** [comment]
#18 is done, #6 I'm going to redo large parts of anyway. So I'll do this now.

**Comment by ttencate** [comment]
I've also fixed all other issues reported by `standard`, and added a pre-commit hook to check this upon commit. Run `githooks/install.sh` to install this hook into your clone, if you like.

**Comment by ttencate** [comment]
Fixed in 543b5c71fbb2e16307b7eed23185bb3811da2da0.
